name: Code coverage > 92 percent

on:
  workflow_run:
    workflows: ["Cargo Build & Test"]
    types:
      - completed

jobs:
  coverage:
    runs-on: ubuntu-22.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: |
          rustup update nightly && rustup default nightly
          # We switch to nightly as we get a report of branch coverage as well.
      - name: Aggressive cleanup
        run: |
          # Remove unnecessary tools to increase available disk space
          # Remove Java (JDKs)
          sudo rm -rf /usr/lib/jvm

          # Remove .NET SDKs
          sudo rm -rf /usr/share/dotnet

          # Remove Swift toolchain
          sudo rm -rf /usr/share/swift

          # Remove Android SDKs
          sudo rm -rf /usr/local/lib/android

          # print available disk space
          df -h
      - name: Generate code coverage
        id: llvm_cov_run
        run: |
          # install code coverage tool and measure coverage
          cargo install cargo-llvm-cov
          cargo llvm-cov --all-features --workspace --json --summary-only --output-path ./output.json
          functions=$(jq -r '.data[0].totals.functions.percent' ./output.json | head -c 2)
          lines=$(jq -r '.data[0].totals.lines.percent' ./output.json | head -c 2)
          regions=$(jq -r '.data[0].totals.regions.percent' ./output.json | head -c 2)
          branches=$(jq -r '.data[0].totals.branches.percent' ./output.json | head -c 2)
          echo "function coverage: $functions"
          echo "lines coverage: $lines"
          echo "regions coverage: $regions"
          echo "branches coverage: $branches"
          if [ "$regions" -le 92 ]; then
            exit 1;
          fi;
          rm ./output.json
